spring:
    thymeleaf:
        cache: true
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
        excluded-view-names: ''
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/moviedb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    redis:
        host: localhost
        port: 6379
        password: 123456
    server:
        port: 8089
alipay:
    appId : 2021000148681545
    appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCkfigQlr+q1H7N3Qaups8/bKjdf/hA6sv6O+x8eO3K/O6PdEqzb5GYWJ/kGcIxftN9K1yaAcdKVTIkqyxj0wKsqIBLTMVD42uVxIYKJFkv02Ki8Zzrgk9i9ywnsMESk1rrCC8LNIv4KXNAk4K4BYtJ/zmvO+LoCV8efOtVr4du6AJAwyRd3cqpp8i0J9dGDXlWLYAeui6cSQZ+ediWmSuTH67JSBlvUCBErmj4u/l285H6JdKj5nkONJi73A3pM+0FDTNqL356/ZYPIyGwTYhP40wICrkzT5gfCZrxzkVEBcANQ9C9dVRak4YBAF5Hf4Hng4+6ZoVsJB/K3meAJbjbAgMBAAECggEBAIShG9jUU9J/54ZBkqO76Brxl+6QwjBFoRYwvutV7hXfftK4J4sqiDBYNQOMKWITKp8gGVgr2u56ZyXdxrruZpekfV05l0y30AVAIfuHd0nynPNY8PeLaEsZlMaj4+kAWyxqutPEGJ+NfFozFhEel0KgwXgjRz9kXweMHYxHLWIj7fkr7iGBMAFe82889PxCRiZ7uc0zbjTHyayMyMXqfogIY2aUuZvrMJN1YqoedNtjzo0dQSMPHyCFzfH4BaiovqVoenoy/OrOtaVxa5ufo9OdF4hQv6HbOHrD49KCvRp+eRBcKNk7C9o8VXcqUocR53d77T2zyIK/spM4eaQVyQECgYEA6fD8GNgHLo2PDMq9ZGHVz8UhOMRLkecyHu1T0gGjoV71HdRPYdJqG8r3JdKsee70lLyiMs3O8EguvES/TEFVhnnKY4jJ/j5pdbNcQsrna0EyjMiN3epM+Aklw5i9FByPA6eEqD4l+jb/EWtXGxsifbfoBZATl8ciIqHeZ2ilsBsCgYEAtADIC9/V4q8CoQD38KR8LFRHCu+reSgNdwtAGlDFCIKshXhvUpRvl8mw9Djri9jXDOTH5MiX8fY96UuCxE6q3eLJ0CYCPRxESODVlWXh1CO9oNObKjOI40fWG9HrKdyivKyllRZ7e0AsCSIUOUEikXBiG6HMGecMfFPIXsDQJkECgYArWWxdbipmhfSr+iV+JGLqTS0Kx9T5BE5VTMTrdUJM9LuW+3B6P/NJkyKY76DmN1E6/nlP0LM38yg12sdX6gNfF9JY/0/uvMHt/X5rIg4f4cTsMX2YUYJRs+A7jmH7CA+4LaJ3SozfALHjGHDbpPuPMDTeUwROa6f3oucDYnDRYQKBgGcQG3pRCxHjysmM2Gm8hCyNhK/KUo/oUu1aT7XBkU8yIr25G2RZARwTq3HqNVO5MEh9pcZk5DryFrjBN3pW4JZzB8JaQOXkjWR89023K/pfDHBNOIaNQ09/DiSXqOIrJjKJV7VpTgJf19bS4Gl31ecYRdQ0a7xZAlkdT5iRJZ0BAoGBAIvvqEeImpVCcKn+bMs8KipDy5ekh94jSLnOwmG0YfF/4Pkr+tMrBn+xnq8dokSkStI+SZZAWX42Eq88i+6rgaCLh/+pLA+DHHbdia0x0AAD+vV8vzarE26Qca/p0n0d4sA5R0n3PN0IXlYUczdy9/Aq2nlh/YKAaiETedobXebf
    alipayPublicKey : MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnW+UJA7JpT5F7coZVDIbEmjsNVsAMSVc1fyBwi3lXqMIUacKEog0CjrwvProcEXoOQmJ7C5ERw6mc0p2z2qSagLg6FKh2lpRxPXjt07fiIk0nKaLz7BdFMhpmsHXM9dtcUuIci/fJd8To0h7xEptMmnwSTU9Y6IxzZ08ElrvXnj85x8SdScmr5dh6j6TTfGl2Ln4NGycYspKCu3U3CEQ7bLTxqeJM1yWsMmxS4R7EhE6L9bgmhDIi8KjA5/EbeDZXB0bmhZTke5K7i9grZAelpjK4MHIekiuS08wpzGXOPzeiU58NmqhIoxchiXTzb0iXemQwrWNJTm/BYwShIAnnwIDAQAB
    notifyUrl : http://u9d5a7ed.natappfree.cc/alipay/notify
    gateway: https://openapi-sandbox.dl.alipaydev.com/gateway.do





